# Static Deployment Configuration for Replit
# Optimized for minimal size and single port

[deploy]
primaryPort = 5000
deploymentTarget = "static"
ignorePorts = true

[deployment]
build = ["sh", "./build-static-optimized.sh"]
run = ["node", "dist/index.js"]
deploymentTarget = "static"
publicDir = "dist/public"
excludeFrom = [
  "node_modules/**",
  "ai-services/**", 
  "attached_assets/**",
  "documentations/**",
  "*.md",
  "*.txt",
  "*.pdf",
  "*.mp4",
  "*.pkl",
  "Screenshot*.png",
  "docker-compose*.yml",
  "Dockerfile*",
  "test_*.py",
  "*.log"
]

[env]
PORT = "5000"
NODE_ENV = "production"