[run]
command = "npm run dev"

# DEPLOYMENT FIX: Static deployment configuration to avoid Cloud Run 8GiB limits
[deployment]
build = ["bash", "build-static-optimized.sh"]
run = ["node", "dist/index.js"]
deploymentTarget = "static"

[nix]
channel = "stable-21_11"

[env]
NODE_ENV = "production"
PORT = "5000"

# CLOUD RUN FIX: Single port configuration - no multiple ports
ignorePorts = true