/**
 * Multi-Organization Branding Service
 * Handles custom branding configurations for different agency organizations
 */

export interface BrandingConfig {
  // Logo & Visual Identity
  logoUrl?: string;
  companyName: string;
  tagline?: string;
  
  // Color Scheme
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  textColor: string;
  backgroundColor: string;
  
  // Typography
  headerFont?: string;
  bodyFont?: string;
  
  // Contact Information
  contactInfo: {
    address?: string;
    phone?: string;
    email?: string;
    website?: string;
    licenseNumbers?: string[];
  };
  
  // PDF Layout Preferences
  layout: {
    headerHeight: number;
    footerHeight: number;
    margins: {
      top: number;
      bottom: number;
      left: number;
      right: number;
    };
    showWatermark?: boolean;
    watermarkText?: string;
  };
  
  // Legal & Compliance
  disclaimers: {
    confidentiality: string;
    liability?: string;
    dataProtection?: string;
  };
  
  // Custom Sections
  customSections?: {
    showCompanyProfile?: boolean;
    showTestimonials?: boolean;
    showCertifications?: boolean;
  };
}

// Default Ark Sports Management branding (will be replaced with user's guidelines)
export const arkSportsBranding: BrandingConfig = {
  companyName: "Ark Sports Management",
  tagline: "Shaping Talents, Creating Legends",
  primaryColor: "#000000", // Rich Black
  secondaryColor: "#FECF0D", // Jonquil Yellow
  accentColor: "#F8A800", // Gold
  textColor: "#000000", // Rich Black
  backgroundColor: "#FFFFFF", // White
  contactInfo: {
    address: "Accra, Ghana & London, UK",
    phone: "+233-24-123-4567",
    email: "info@arksportsmanagement.com",
    website: "www.arksportsmanagement.com",
    licenseNumbers: ["FIFA Agent License: GHA-FA-2024-001", "FA Agent License: UK-FA-2024-ARK"]
  },
  layout: {
    headerHeight: 80,
    footerHeight: 60,
    margins: {
      top: 100,
      bottom: 80,
      left: 40,
      right: 40
    },
    showWatermark: true,
    watermarkText: "ARK SPORTS CONFIDENTIAL"
  },
  disclaimers: {
    confidentiality: "This document contains confidential player information intended solely for the recipient. Unauthorized disclosure is strictly prohibited and may result in legal action.",
    liability: "All player assessments are based on available data and professional analysis. Ark Sports Management assumes no liability for investment decisions based on this report.",
    dataProtection: "Player data handled in compliance with GDPR and Ghana Data Protection Act 2012."
  },
  customSections: {
    showCompanyProfile: true,
    showCertifications: true,
    showTestimonials: false
  }
};

// Default PlatinumEdge branding for non-agency users
export const defaultBranding: BrandingConfig = {
  companyName: "PlatinumEdge Analytics",
  tagline: "Advanced Football Analytics Platform",
  primaryColor: "#2563eb",
  secondaryColor: "#10b981",
  accentColor: "#f59e0b",
  textColor: "#374151",
  backgroundColor: "#ffffff",
  contactInfo: {
    email: "support@platinumedge.com",
    website: "www.platinumedge.com"
  },
  layout: {
    headerHeight: 70,
    footerHeight: 50,
    margins: {
      top: 90,
      bottom: 70,
      left: 40,
      right: 40
    }
  },
  disclaimers: {
    confidentiality: "This player analysis report is generated by PlatinumEdge Analytics platform."
  }
};

/**
 * Get branding configuration for an organization
 */
export function getBrandingConfig(organizationId?: number, organizationData?: any): BrandingConfig {
  // If user belongs to an agency organization with custom branding
  if (organizationData?.type === 'agency' && organizationData?.brandingConfig) {
    return {
      ...defaultBranding,
      ...organizationData.brandingConfig
    };
  }
  
  // Special handling for known agencies
  if (organizationData?.name === 'Ark Sports Management') {
    return arkSportsBranding;
  }
  
  // Default branding for all other users
  return defaultBranding;
}

/**
 * Create custom branding configuration
 */
export function createCustomBranding(config: Partial<BrandingConfig>): BrandingConfig {
  return {
    ...defaultBranding,
    ...config,
    contactInfo: {
      ...defaultBranding.contactInfo,
      ...config.contactInfo
    },
    layout: {
      ...defaultBranding.layout,
      ...config.layout,
      margins: {
        ...defaultBranding.layout.margins,
        ...config.layout?.margins
      }
    },
    disclaimers: {
      ...defaultBranding.disclaimers,
      ...config.disclaimers
    }
  };
}

/**
 * Validate branding configuration
 */
export function validateBrandingConfig(config: BrandingConfig): boolean {
  const requiredFields = [
    'companyName',
    'primaryColor',
    'secondaryColor',
    'textColor',
    'backgroundColor'
  ];
  
  return requiredFields.every(field => {
    const value = (config as any)[field];
    return value && value.trim().length > 0;
  });
}